name: build

on:
  push:
    paths:
      - 'neuroconda_basepackages.yml'

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Free up 24GB of disk space
      run: sudo rm -rf /usr/share/dotnet # hackity hack
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install mamba
      run: conda install -c conda-forge -y mamba
    - name: Build environment
      run: |
        rm neuroconda.yml
        make update
      timeout-minutes: 360
    - name: Install environment
      run: |
        make install
    - name: Basic test
      run: |
        conda env list | grep neuroconda
